// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/sync/v1/sync.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaselineChoice int32

const (
	BaselineChoice_BASELINE_CHOICE_UNSPECIFIED BaselineChoice = 0
	BaselineChoice_BASELINE_CHOICE_USE_LOCAL   BaselineChoice = 1
	BaselineChoice_BASELINE_CHOICE_USE_SERVER  BaselineChoice = 2
)

// Enum value maps for BaselineChoice.
var (
	BaselineChoice_name = map[int32]string{
		0: "BASELINE_CHOICE_UNSPECIFIED",
		1: "BASELINE_CHOICE_USE_LOCAL",
		2: "BASELINE_CHOICE_USE_SERVER",
	}
	BaselineChoice_value = map[string]int32{
		"BASELINE_CHOICE_UNSPECIFIED": 0,
		"BASELINE_CHOICE_USE_LOCAL":   1,
		"BASELINE_CHOICE_USE_SERVER":  2,
	}
)

func (x BaselineChoice) Enum() *BaselineChoice {
	p := new(BaselineChoice)
	*p = x
	return p
}

func (x BaselineChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaselineChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sync_v1_sync_proto_enumTypes[0].Descriptor()
}

func (BaselineChoice) Type() protoreflect.EnumType {
	return &file_api_sync_v1_sync_proto_enumTypes[0]
}

func (x BaselineChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaselineChoice.Descriptor instead.
func (BaselineChoice) EnumDescriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

// 这些字段编号必须与旧版 src/sync/protocol.js 保持一致。
type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	EntityKey     string                 `protobuf:"bytes,2,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	BaseVersion   uint64                 `protobuf:"varint,3,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	ClientTimeMs  uint64                 `protobuf:"varint,4,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,5,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Deleted       bool                   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeviceId      string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,8,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *Mutation) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *Mutation) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *Mutation) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *Mutation) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *Mutation) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Mutation) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Mutation) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

type MutationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	ServerCursor  uint64                 `protobuf:"varint,2,opt,name=server_cursor,json=serverCursor,proto3" json:"server_cursor,omitempty"`
	Conflict      bool                   `protobuf:"varint,3,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Applied       bool                   `protobuf:"varint,4,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationAck) Reset() {
	*x = MutationAck{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationAck) ProtoMessage() {}

func (x *MutationAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationAck.ProtoReflect.Descriptor instead.
func (*MutationAck) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *MutationAck) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *MutationAck) GetServerCursor() uint64 {
	if x != nil {
		return x.ServerCursor
	}
	return 0
}

func (x *MutationAck) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

func (x *MutationAck) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	EntityKey     string                 `protobuf:"bytes,2,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,3,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientTimeMs  uint64                 `protobuf:"varint,6,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	OpId          string                 `protobuf:"bytes,7,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *Change) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *Change) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *Change) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Change) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Change) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *Change) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type SyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Cursor           uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Mutations        []*Mutation            `protobuf:"bytes,3,rep,name=mutations,proto3" json:"mutations,omitempty"`
	PullLimit        uint32                 `protobuf:"varint,4,opt,name=pull_limit,json=pullLimit,proto3" json:"pull_limit,omitempty"`
	BaselineId       string                 `protobuf:"bytes,5,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	LocalVersion     uint64                 `protobuf:"varint,6,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	LocalUpdatedAtMs uint64                 `protobuf:"varint,7,opt,name=local_updated_at_ms,json=localUpdatedAtMs,proto3" json:"local_updated_at_ms,omitempty"`
	LocalProgressDay string                 `protobuf:"bytes,8,opt,name=local_progress_day,json=localProgressDay,proto3" json:"local_progress_day,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SyncRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *SyncRequest) GetPullLimit() uint32 {
	if x != nil {
		return x.PullLimit
	}
	return 0
}

func (x *SyncRequest) GetBaselineId() string {
	if x != nil {
		return x.BaselineId
	}
	return ""
}

func (x *SyncRequest) GetLocalVersion() uint64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *SyncRequest) GetLocalUpdatedAtMs() uint64 {
	if x != nil {
		return x.LocalUpdatedAtMs
	}
	return 0
}

func (x *SyncRequest) GetLocalProgressDay() string {
	if x != nil {
		return x.LocalProgressDay
	}
	return ""
}

type SyncResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NextCursor        uint64                 `protobuf:"varint,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Acks              []*MutationAck         `protobuf:"bytes,2,rep,name=acks,proto3" json:"acks,omitempty"`
	Changes           []*Change              `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	HasMore           bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ResetRequired     bool                   `protobuf:"varint,5,opt,name=reset_required,json=resetRequired,proto3" json:"reset_required,omitempty"`
	BaselineId        string                 `protobuf:"bytes,6,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerVersion     uint64                 `protobuf:"varint,7,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerUpdatedAtMs uint64                 `protobuf:"varint,8,opt,name=server_updated_at_ms,json=serverUpdatedAtMs,proto3" json:"server_updated_at_ms,omitempty"`
	ServerProgressDay string                 `protobuf:"bytes,9,opt,name=server_progress_day,json=serverProgressDay,proto3" json:"server_progress_day,omitempty"`
	BaselineMismatch  bool                   `protobuf:"varint,10,opt,name=baseline_mismatch,json=baselineMismatch,proto3" json:"baseline_mismatch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *SyncResponse) GetAcks() []*MutationAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *SyncResponse) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncResponse) GetResetRequired() bool {
	if x != nil {
		return x.ResetRequired
	}
	return false
}

func (x *SyncResponse) GetBaselineId() string {
	if x != nil {
		return x.BaselineId
	}
	return ""
}

func (x *SyncResponse) GetServerVersion() uint64 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

func (x *SyncResponse) GetServerUpdatedAtMs() uint64 {
	if x != nil {
		return x.ServerUpdatedAtMs
	}
	return 0
}

func (x *SyncResponse) GetServerProgressDay() string {
	if x != nil {
		return x.ServerProgressDay
	}
	return ""
}

func (x *SyncResponse) GetBaselineMismatch() bool {
	if x != nil {
		return x.BaselineMismatch
	}
	return false
}

type ResolveBaselineRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestId                string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeviceId                 string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LocalBaselineId          string                 `protobuf:"bytes,3,opt,name=local_baseline_id,json=localBaselineId,proto3" json:"local_baseline_id,omitempty"`
	ExpectedServerBaselineId string                 `protobuf:"bytes,4,opt,name=expected_server_baseline_id,json=expectedServerBaselineId,proto3" json:"expected_server_baseline_id,omitempty"`
	ExpectedServerVersion    uint64                 `protobuf:"varint,5,opt,name=expected_server_version,json=expectedServerVersion,proto3" json:"expected_server_version,omitempty"`
	Choice                   BaselineChoice         `protobuf:"varint,6,opt,name=choice,proto3,enum=stella.sync.v1.BaselineChoice" json:"choice,omitempty"`
	LocalSnapshot            []*Mutation            `protobuf:"bytes,7,rep,name=local_snapshot,json=localSnapshot,proto3" json:"local_snapshot,omitempty"`
	LocalVersion             uint64                 `protobuf:"varint,8,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	LocalUpdatedAtMs         uint64                 `protobuf:"varint,9,opt,name=local_updated_at_ms,json=localUpdatedAtMs,proto3" json:"local_updated_at_ms,omitempty"`
	LocalProgressDay         string                 `protobuf:"bytes,10,opt,name=local_progress_day,json=localProgressDay,proto3" json:"local_progress_day,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResolveBaselineRequest) Reset() {
	*x = ResolveBaselineRequest{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBaselineRequest) ProtoMessage() {}

func (x *ResolveBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBaselineRequest.ProtoReflect.Descriptor instead.
func (*ResolveBaselineRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveBaselineRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolveBaselineRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ResolveBaselineRequest) GetLocalBaselineId() string {
	if x != nil {
		return x.LocalBaselineId
	}
	return ""
}

func (x *ResolveBaselineRequest) GetExpectedServerBaselineId() string {
	if x != nil {
		return x.ExpectedServerBaselineId
	}
	return ""
}

func (x *ResolveBaselineRequest) GetExpectedServerVersion() uint64 {
	if x != nil {
		return x.ExpectedServerVersion
	}
	return 0
}

func (x *ResolveBaselineRequest) GetChoice() BaselineChoice {
	if x != nil {
		return x.Choice
	}
	return BaselineChoice_BASELINE_CHOICE_UNSPECIFIED
}

func (x *ResolveBaselineRequest) GetLocalSnapshot() []*Mutation {
	if x != nil {
		return x.LocalSnapshot
	}
	return nil
}

func (x *ResolveBaselineRequest) GetLocalVersion() uint64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *ResolveBaselineRequest) GetLocalUpdatedAtMs() uint64 {
	if x != nil {
		return x.LocalUpdatedAtMs
	}
	return 0
}

func (x *ResolveBaselineRequest) GetLocalProgressDay() string {
	if x != nil {
		return x.LocalProgressDay
	}
	return ""
}

type ResolveBaselineResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaselineId        string                 `protobuf:"bytes,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerVersion     uint64                 `protobuf:"varint,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerUpdatedAtMs uint64                 `protobuf:"varint,3,opt,name=server_updated_at_ms,json=serverUpdatedAtMs,proto3" json:"server_updated_at_ms,omitempty"`
	ServerProgressDay string                 `protobuf:"bytes,4,opt,name=server_progress_day,json=serverProgressDay,proto3" json:"server_progress_day,omitempty"`
	Records           []*Change              `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	Stale             bool                   `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	ServerCursor      uint64                 `protobuf:"varint,7,opt,name=server_cursor,json=serverCursor,proto3" json:"server_cursor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveBaselineResponse) Reset() {
	*x = ResolveBaselineResponse{}
	mi := &file_api_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBaselineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBaselineResponse) ProtoMessage() {}

func (x *ResolveBaselineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBaselineResponse.ProtoReflect.Descriptor instead.
func (*ResolveBaselineResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveBaselineResponse) GetBaselineId() string {
	if x != nil {
		return x.BaselineId
	}
	return ""
}

func (x *ResolveBaselineResponse) GetServerVersion() uint64 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

func (x *ResolveBaselineResponse) GetServerUpdatedAtMs() uint64 {
	if x != nil {
		return x.ServerUpdatedAtMs
	}
	return 0
}

func (x *ResolveBaselineResponse) GetServerProgressDay() string {
	if x != nil {
		return x.ServerProgressDay
	}
	return ""
}

func (x *ResolveBaselineResponse) GetRecords() []*Change {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ResolveBaselineResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *ResolveBaselineResponse) GetServerCursor() uint64 {
	if x != nil {
		return x.ServerCursor
	}
	return 0
}

var File_api_sync_v1_sync_proto protoreflect.FileDescriptor

const file_api_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x16api/sync/v1/sync.proto\x12\x0estella.sync.v1\"\xfc\x01\n" +
	"\bMutation\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x02 \x01(\tR\tentityKey\x12!\n" +
	"\fbase_version\x18\x03 \x01(\x04R\vbaseVersion\x12$\n" +
	"\x0eclient_time_ms\x18\x04 \x01(\x04R\fclientTimeMs\x12\x1d\n" +
	"\n" +
	"value_json\x18\x05 \x01(\fR\tvalueJson\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"client_seq\x18\b \x01(\x04R\tclientSeq\"}\n" +
	"\vMutationAck\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12#\n" +
	"\rserver_cursor\x18\x02 \x01(\x04R\fserverCursor\x12\x1a\n" +
	"\bconflict\x18\x03 \x01(\bR\bconflict\x12\x18\n" +
	"\aapplied\x18\x04 \x01(\bR\aapplied\"\xd0\x01\n" +
	"\x06Change\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x02 \x01(\tR\tentityKey\x12\x1d\n" +
	"\n" +
	"value_json\x18\x03 \x01(\fR\tvalueJson\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12$\n" +
	"\x0eclient_time_ms\x18\x06 \x01(\x04R\fclientTimeMs\x12\x13\n" +
	"\x05op_id\x18\a \x01(\tR\x04opId\"\xbc\x02\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x126\n" +
	"\tmutations\x18\x03 \x03(\v2\x18.stella.sync.v1.MutationR\tmutations\x12\x1d\n" +
	"\n" +
	"pull_limit\x18\x04 \x01(\rR\tpullLimit\x12\x1f\n" +
	"\vbaseline_id\x18\x05 \x01(\tR\n" +
	"baselineId\x12#\n" +
	"\rlocal_version\x18\x06 \x01(\x04R\flocalVersion\x12-\n" +
	"\x13local_updated_at_ms\x18\a \x01(\x04R\x10localUpdatedAtMs\x12,\n" +
	"\x12local_progress_day\x18\b \x01(\tR\x10localProgressDay\"\xaa\x03\n" +
	"\fSyncResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\x04R\n" +
	"nextCursor\x12/\n" +
	"\x04acks\x18\x02 \x03(\v2\x1b.stella.sync.v1.MutationAckR\x04acks\x120\n" +
	"\achanges\x18\x03 \x03(\v2\x16.stella.sync.v1.ChangeR\achanges\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12%\n" +
	"\x0ereset_required\x18\x05 \x01(\bR\rresetRequired\x12\x1f\n" +
	"\vbaseline_id\x18\x06 \x01(\tR\n" +
	"baselineId\x12%\n" +
	"\x0eserver_version\x18\a \x01(\x04R\rserverVersion\x12/\n" +
	"\x14server_updated_at_ms\x18\b \x01(\x04R\x11serverUpdatedAtMs\x12.\n" +
	"\x13server_progress_day\x18\t \x01(\tR\x11serverProgressDay\x12+\n" +
	"\x11baseline_mismatch\x18\n" +
	" \x01(\bR\x10baselineMismatch\"\xf2\x03\n" +
	"\x16ResolveBaselineRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12*\n" +
	"\x11local_baseline_id\x18\x03 \x01(\tR\x0flocalBaselineId\x12=\n" +
	"\x1bexpected_server_baseline_id\x18\x04 \x01(\tR\x18expectedServerBaselineId\x126\n" +
	"\x17expected_server_version\x18\x05 \x01(\x04R\x15expectedServerVersion\x126\n" +
	"\x06choice\x18\x06 \x01(\x0e2\x1e.stella.sync.v1.BaselineChoiceR\x06choice\x12?\n" +
	"\x0elocal_snapshot\x18\a \x03(\v2\x18.stella.sync.v1.MutationR\rlocalSnapshot\x12#\n" +
	"\rlocal_version\x18\b \x01(\x04R\flocalVersion\x12-\n" +
	"\x13local_updated_at_ms\x18\t \x01(\x04R\x10localUpdatedAtMs\x12,\n" +
	"\x12local_progress_day\x18\n" +
	" \x01(\tR\x10localProgressDay\"\xaf\x02\n" +
	"\x17ResolveBaselineResponse\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\tR\n" +
	"baselineId\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\x04R\rserverVersion\x12/\n" +
	"\x14server_updated_at_ms\x18\x03 \x01(\x04R\x11serverUpdatedAtMs\x12.\n" +
	"\x13server_progress_day\x18\x04 \x01(\tR\x11serverProgressDay\x120\n" +
	"\arecords\x18\x05 \x03(\v2\x16.stella.sync.v1.ChangeR\arecords\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\bR\x05stale\x12#\n" +
	"\rserver_cursor\x18\a \x01(\x04R\fserverCursor*p\n" +
	"\x0eBaselineChoice\x12\x1f\n" +
	"\x1bBASELINE_CHOICE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19BASELINE_CHOICE_USE_LOCAL\x10\x01\x12\x1e\n" +
	"\x1aBASELINE_CHOICE_USE_SERVER\x10\x02B:Z8github.com/Luminet2023/hifumi-backend/api/sync/v1;syncv1b\x06proto3"

var (
	file_api_sync_v1_sync_proto_rawDescOnce sync.Once
	file_api_sync_v1_sync_proto_rawDescData []byte
)

func file_api_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_api_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_api_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sync_v1_sync_proto_rawDesc), len(file_api_sync_v1_sync_proto_rawDesc)))
	})
	return file_api_sync_v1_sync_proto_rawDescData
}

var file_api_sync_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_sync_v1_sync_proto_goTypes = []any{
	(BaselineChoice)(0),             // 0: stella.sync.v1.BaselineChoice
	(*Mutation)(nil),                // 1: stella.sync.v1.Mutation
	(*MutationAck)(nil),             // 2: stella.sync.v1.MutationAck
	(*Change)(nil),                  // 3: stella.sync.v1.Change
	(*SyncRequest)(nil),             // 4: stella.sync.v1.SyncRequest
	(*SyncResponse)(nil),            // 5: stella.sync.v1.SyncResponse
	(*ResolveBaselineRequest)(nil),  // 6: stella.sync.v1.ResolveBaselineRequest
	(*ResolveBaselineResponse)(nil), // 7: stella.sync.v1.ResolveBaselineResponse
}
var file_api_sync_v1_sync_proto_depIdxs = []int32{
	1, // 0: stella.sync.v1.SyncRequest.mutations:type_name -> stella.sync.v1.Mutation
	2, // 1: stella.sync.v1.SyncResponse.acks:type_name -> stella.sync.v1.MutationAck
	3, // 2: stella.sync.v1.SyncResponse.changes:type_name -> stella.sync.v1.Change
	0, // 3: stella.sync.v1.ResolveBaselineRequest.choice:type_name -> stella.sync.v1.BaselineChoice
	1, // 4: stella.sync.v1.ResolveBaselineRequest.local_snapshot:type_name -> stella.sync.v1.Mutation
	3, // 5: stella.sync.v1.ResolveBaselineResponse.records:type_name -> stella.sync.v1.Change
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_sync_v1_sync_proto_init() }
func file_api_sync_v1_sync_proto_init() {
	if File_api_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sync_v1_sync_proto_rawDesc), len(file_api_sync_v1_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_api_sync_v1_sync_proto_depIdxs,
		EnumInfos:         file_api_sync_v1_sync_proto_enumTypes,
		MessageInfos:      file_api_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_api_sync_v1_sync_proto = out.File
	file_api_sync_v1_sync_proto_goTypes = nil
	file_api_sync_v1_sync_proto_depIdxs = nil
}
